apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/sales/
patches:
- path: ./dev-sales-patch-deploy.yaml
images:
- name: service-image
  newName: ardanlabs/service/sales-api
  newTag: 0.0.1
